// Code generated for SigmarWater service
// © SigmarWater 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/SigmarWater/messenger/auth/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// UserCache is an autogenerated mock type for the UserCache type
type UserCache struct {
	mock.Mock
}

type UserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *UserCache) EXPECT() *UserCache_Expecter {
	return &UserCache_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, uuid
func (_m *UserCache) Del(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCache_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type UserCache_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UserCache_Expecter) Del(ctx interface{}, uuid interface{}) *UserCache_Del_Call {
	return &UserCache_Del_Call{Call: _e.mock.On("Del", ctx, uuid)}
}

func (_c *UserCache_Del_Call) Run(run func(ctx context.Context, uuid string)) *UserCache_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserCache_Del_Call) Return(_a0 error) *UserCache_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCache_Del_Call) RunAndReturn(run func(context.Context, string) error) *UserCache_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *UserCache) Get(ctx context.Context, uuid string) (*model.UserService, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserService, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserService); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UserCache_Expecter) Get(ctx interface{}, uuid interface{}) *UserCache_Get_Call {
	return &UserCache_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *UserCache_Get_Call) Run(run func(ctx context.Context, uuid string)) *UserCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserCache_Get_Call) Return(_a0 *model.UserService, _a1 error) *UserCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserCache_Get_Call) RunAndReturn(run func(context.Context, string) (*model.UserService, error)) *UserCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, uuid, user, ttl
func (_m *UserCache) Set(ctx context.Context, uuid string, user model.UserService, ttl time.Duration) error {
	ret := _m.Called(ctx, uuid, user, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.UserService, time.Duration) error); ok {
		r0 = rf(ctx, uuid, user, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type UserCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - user model.UserService
//   - ttl time.Duration
func (_e *UserCache_Expecter) Set(ctx interface{}, uuid interface{}, user interface{}, ttl interface{}) *UserCache_Set_Call {
	return &UserCache_Set_Call{Call: _e.mock.On("Set", ctx, uuid, user, ttl)}
}

func (_c *UserCache_Set_Call) Run(run func(ctx context.Context, uuid string, user model.UserService, ttl time.Duration)) *UserCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.UserService), args[3].(time.Duration))
	})
	return _c
}

func (_c *UserCache_Set_Call) Return(_a0 error) *UserCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserCache_Set_Call) RunAndReturn(run func(context.Context, string, model.UserService, time.Duration) error) *UserCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserCache creates a new instance of UserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCache {
	mock := &UserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
