// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/jwt_service/jwt_service.proto

package jwt_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccessToken          string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpireAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=access_token_expire_at,json=accessTokenExpireAt,proto3" json:"access_token_expire_at,omitempty"`
	RefreshTokenExpireAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=refresh_token_expire_at,json=refreshTokenExpireAt,proto3" json:"refresh_token_expire_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetAccessTokenExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpireAt
	}
	return nil
}

func (x *LoginResponse) GetRefreshTokenExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpireAt
	}
	return nil
}

type GetAccessTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessTokenRequest) Reset() {
	*x = GetAccessTokenRequest{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenRequest) ProtoMessage() {}

func (x *GetAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*GetAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccessTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetAccessTokenResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessToken         string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpireAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=access_token_expire_at,json=accessTokenExpireAt,proto3" json:"access_token_expire_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAccessTokenResponse) Reset() {
	*x = GetAccessTokenResponse{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessTokenResponse) ProtoMessage() {}

func (x *GetAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*GetAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccessTokenResponse) GetAccessTokenExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessTokenExpireAt
	}
	return nil
}

type GetRefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRefreshTokenRequest) Reset() {
	*x = GetRefreshTokenRequest{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefreshTokenRequest) ProtoMessage() {}

func (x *GetRefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*GetRefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetRefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type GetRefreshTokenResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken         string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	RefreshTokenExpireAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=refresh_token_expire_at,json=refreshTokenExpireAt,proto3" json:"refresh_token_expire_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRefreshTokenResponse) Reset() {
	*x = GetRefreshTokenResponse{}
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRefreshTokenResponse) ProtoMessage() {}

func (x *GetRefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_jwt_service_jwt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*GetRefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_jwt_service_jwt_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetRefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GetRefreshTokenResponse) GetRefreshTokenExpireAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RefreshTokenExpireAt
	}
	return nil
}

var File_api_jwt_service_jwt_service_proto protoreflect.FileDescriptor

const file_api_jwt_service_jwt_service_proto_rawDesc = "" +
	"\n" +
	"!api/jwt_service/jwt_service.proto\x12#messenger.jwt.ptoto.api.jwt_service\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xfb\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12O\n" +
	"\x16access_token_expire_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x13accessTokenExpireAt\x12Q\n" +
	"\x17refresh_token_expire_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x14refreshTokenExpireAt\"<\n" +
	"\x15GetAccessTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x8c\x01\n" +
	"\x16GetAccessTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12O\n" +
	"\x16access_token_expire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x13accessTokenExpireAt\"=\n" +
	"\x16GetRefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x91\x01\n" +
	"\x17GetRefreshTokenResponse\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12Q\n" +
	"\x17refresh_token_expire_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x14refreshTokenExpireAt2\x97\x03\n" +
	"\n" +
	"JWTService\x12n\n" +
	"\x05Login\x121.messenger.jwt.ptoto.api.jwt_service.LoginRequest\x1a2.messenger.jwt.ptoto.api.jwt_service.LoginResponse\x12\x89\x01\n" +
	"\x0eGetAccessToken\x12:.messenger.jwt.ptoto.api.jwt_service.GetAccessTokenRequest\x1a;.messenger.jwt.ptoto.api.jwt_service.GetAccessTokenResponse\x12\x8c\x01\n" +
	"\x0fGetRefreshToken\x12;.messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenRequest\x1a<.messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenResponseB#Z!messenger/jwt/pkg/api/jwt_serviceb\x06proto3"

var (
	file_api_jwt_service_jwt_service_proto_rawDescOnce sync.Once
	file_api_jwt_service_jwt_service_proto_rawDescData []byte
)

func file_api_jwt_service_jwt_service_proto_rawDescGZIP() []byte {
	file_api_jwt_service_jwt_service_proto_rawDescOnce.Do(func() {
		file_api_jwt_service_jwt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jwt_service_jwt_service_proto_rawDesc), len(file_api_jwt_service_jwt_service_proto_rawDesc)))
	})
	return file_api_jwt_service_jwt_service_proto_rawDescData
}

var file_api_jwt_service_jwt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_jwt_service_jwt_service_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: messenger.jwt.ptoto.api.jwt_service.LoginRequest
	(*LoginResponse)(nil),           // 1: messenger.jwt.ptoto.api.jwt_service.LoginResponse
	(*GetAccessTokenRequest)(nil),   // 2: messenger.jwt.ptoto.api.jwt_service.GetAccessTokenRequest
	(*GetAccessTokenResponse)(nil),  // 3: messenger.jwt.ptoto.api.jwt_service.GetAccessTokenResponse
	(*GetRefreshTokenRequest)(nil),  // 4: messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenRequest
	(*GetRefreshTokenResponse)(nil), // 5: messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenResponse
	(*timestamppb.Timestamp)(nil),   // 6: google.protobuf.Timestamp
}
var file_api_jwt_service_jwt_service_proto_depIdxs = []int32{
	6, // 0: messenger.jwt.ptoto.api.jwt_service.LoginResponse.access_token_expire_at:type_name -> google.protobuf.Timestamp
	6, // 1: messenger.jwt.ptoto.api.jwt_service.LoginResponse.refresh_token_expire_at:type_name -> google.protobuf.Timestamp
	6, // 2: messenger.jwt.ptoto.api.jwt_service.GetAccessTokenResponse.access_token_expire_at:type_name -> google.protobuf.Timestamp
	6, // 3: messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenResponse.refresh_token_expire_at:type_name -> google.protobuf.Timestamp
	0, // 4: messenger.jwt.ptoto.api.jwt_service.JWTService.Login:input_type -> messenger.jwt.ptoto.api.jwt_service.LoginRequest
	2, // 5: messenger.jwt.ptoto.api.jwt_service.JWTService.GetAccessToken:input_type -> messenger.jwt.ptoto.api.jwt_service.GetAccessTokenRequest
	4, // 6: messenger.jwt.ptoto.api.jwt_service.JWTService.GetRefreshToken:input_type -> messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenRequest
	1, // 7: messenger.jwt.ptoto.api.jwt_service.JWTService.Login:output_type -> messenger.jwt.ptoto.api.jwt_service.LoginResponse
	3, // 8: messenger.jwt.ptoto.api.jwt_service.JWTService.GetAccessToken:output_type -> messenger.jwt.ptoto.api.jwt_service.GetAccessTokenResponse
	5, // 9: messenger.jwt.ptoto.api.jwt_service.JWTService.GetRefreshToken:output_type -> messenger.jwt.ptoto.api.jwt_service.GetRefreshTokenResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_jwt_service_jwt_service_proto_init() }
func file_api_jwt_service_jwt_service_proto_init() {
	if File_api_jwt_service_jwt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jwt_service_jwt_service_proto_rawDesc), len(file_api_jwt_service_jwt_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_jwt_service_jwt_service_proto_goTypes,
		DependencyIndexes: file_api_jwt_service_jwt_service_proto_depIdxs,
		MessageInfos:      file_api_jwt_service_jwt_service_proto_msgTypes,
	}.Build()
	File_api_jwt_service_jwt_service_proto = out.File
	file_api_jwt_service_jwt_service_proto_goTypes = nil
	file_api_jwt_service_jwt_service_proto_depIdxs = nil
}
