// Code generated for SigmarWater service
// © SigmarWater 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/SigmarWater/messenger/auth/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UsersService is an autogenerated mock type for the UsersService type
type UsersService struct {
	mock.Mock
}

type UsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersService) EXPECT() *UsersService_Expecter {
	return &UsersService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *UsersService) Create(ctx context.Context, user *model.UserService) (int64, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserService) (int64, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.UserService) int64); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.UserService) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UsersService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.UserService
func (_e *UsersService_Expecter) Create(ctx interface{}, user interface{}) *UsersService_Create_Call {
	return &UsersService_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UsersService_Create_Call) Run(run func(ctx context.Context, user *model.UserService)) *UsersService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.UserService))
	})
	return _c
}

func (_c *UsersService_Create_Call) Return(id int64, err error) *UsersService_Create_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *UsersService_Create_Call) RunAndReturn(run func(context.Context, *model.UserService) (int64, error)) *UsersService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *UsersService) Get(ctx context.Context, id int64) (*model.UserService, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.UserService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*model.UserService, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *model.UserService); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsersService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UsersService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UsersService_Expecter) Get(ctx interface{}, id interface{}) *UsersService_Get_Call {
	return &UsersService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UsersService_Get_Call) Run(run func(ctx context.Context, id int64)) *UsersService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UsersService_Get_Call) Return(_a0 *model.UserService, _a1 error) *UsersService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsersService_Get_Call) RunAndReturn(run func(context.Context, int64) (*model.UserService, error)) *UsersService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsersService creates a new instance of UsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersService {
	mock := &UsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
