// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/auth_service/auth_service.proto

package auth_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_service_auth_service_proto protoreflect.FileDescriptor

const file_api_auth_service_auth_service_proto_rawDesc = "" +
	"\n" +
	"#api/auth_service/auth_service.proto\x12%messenger.auth.proto.api.auth_service\x1a\x1bgoogle/protobuf/empty.proto\x1a$api/auth_service/auth_messages.proto\x1a\x1cgoogle/api/annotations.proto2\x8f\x04\n" +
	"\aUserAPI\x12\x8f\x01\n" +
	"\x06Create\x124.messenger.auth.proto.api.auth_service.CreateRequest\x1a5.messenger.auth.proto.api.auth_service.CreateResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12\x88\x01\n" +
	"\x03Get\x121.messenger.auth.proto.api.auth_service.GetRequest\x1a2.messenger.auth.proto.api.auth_service.GetResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}\x12t\n" +
	"\x06Update\x124.messenger.auth.proto.api.auth_service.UpdateRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*2\x11/api/v1/user/{id}\x12q\n" +
	"\x06Delete\x124.messenger.auth.proto.api.auth_service.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/api/v1/user/{id}B%Z#messenger/auth/pkg/api/auth_serviceb\x06proto3"

var file_api_auth_service_auth_service_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: messenger.auth.proto.api.auth_service.CreateRequest
	(*GetRequest)(nil),     // 1: messenger.auth.proto.api.auth_service.GetRequest
	(*UpdateRequest)(nil),  // 2: messenger.auth.proto.api.auth_service.UpdateRequest
	(*DeleteRequest)(nil),  // 3: messenger.auth.proto.api.auth_service.DeleteRequest
	(*CreateResponse)(nil), // 4: messenger.auth.proto.api.auth_service.CreateResponse
	(*GetResponse)(nil),    // 5: messenger.auth.proto.api.auth_service.GetResponse
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_api_auth_service_auth_service_proto_depIdxs = []int32{
	0, // 0: messenger.auth.proto.api.auth_service.UserAPI.Create:input_type -> messenger.auth.proto.api.auth_service.CreateRequest
	1, // 1: messenger.auth.proto.api.auth_service.UserAPI.Get:input_type -> messenger.auth.proto.api.auth_service.GetRequest
	2, // 2: messenger.auth.proto.api.auth_service.UserAPI.Update:input_type -> messenger.auth.proto.api.auth_service.UpdateRequest
	3, // 3: messenger.auth.proto.api.auth_service.UserAPI.Delete:input_type -> messenger.auth.proto.api.auth_service.DeleteRequest
	4, // 4: messenger.auth.proto.api.auth_service.UserAPI.Create:output_type -> messenger.auth.proto.api.auth_service.CreateResponse
	5, // 5: messenger.auth.proto.api.auth_service.UserAPI.Get:output_type -> messenger.auth.proto.api.auth_service.GetResponse
	6, // 6: messenger.auth.proto.api.auth_service.UserAPI.Update:output_type -> google.protobuf.Empty
	6, // 7: messenger.auth.proto.api.auth_service.UserAPI.Delete:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_service_auth_service_proto_init() }
func file_api_auth_service_auth_service_proto_init() {
	if File_api_auth_service_auth_service_proto != nil {
		return
	}
	file_api_auth_service_auth_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_service_auth_service_proto_rawDesc), len(file_api_auth_service_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_service_auth_service_proto_goTypes,
		DependencyIndexes: file_api_auth_service_auth_service_proto_depIdxs,
	}.Build()
	File_api_auth_service_auth_service_proto = out.File
	file_api_auth_service_auth_service_proto_goTypes = nil
	file_api_auth_service_auth_service_proto_depIdxs = nil
}
