// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: api/chat_service/service_chatServer.proto

package chat_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_service_service_chatServer_proto protoreflect.FileDescriptor

const file_api_chat_service_service_chatServer_proto_rawDesc = "" +
	"\n" +
	")api/chat_service/service_chatServer.proto\x12\x1echat.protobuf.api.chat_service\x1a\x1bgoogle/protobuf/empty.proto\x1a*api/chat_service/messages_chatServer.proto\x1a\x1egoogle/protobuf/wrappers.proto2\xa6\x02\n" +
	"\aChatApi\x12g\n" +
	"\x06Create\x12-.chat.protobuf.api.chat_service.CreateRequest\x1a..chat.protobuf.api.chat_service.CreateResponse\x12O\n" +
	"\x06Delete\x12-.chat.protobuf.api.chat_service.DeleteRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\vSendMessage\x122.chat.protobuf.api.chat_service.SendMessageRequest\x1a\x1c.google.protobuf.StringValue(\x01B\xf9\x01\n" +
	"\"com.chat.protobuf.api.chat_serviceB\x16ServiceChatServerProtoP\x01Z#messenger/chat/pkg/api/chat_service\xa2\x02\x04CPAC\xaa\x02\x1dChat.Protobuf.Api.ChatService\xca\x02\x1dChat\\Protobuf\\Api\\ChatService\xe2\x02)Chat\\Protobuf\\Api\\ChatService\\GPBMetadata\xea\x02 Chat::Protobuf::Api::ChatServiceb\x06proto3"

var file_api_chat_service_service_chatServer_proto_goTypes = []any{
	(*CreateRequest)(nil),          // 0: chat.protobuf.api.chat_service.CreateRequest
	(*DeleteRequest)(nil),          // 1: chat.protobuf.api.chat_service.DeleteRequest
	(*SendMessageRequest)(nil),     // 2: chat.protobuf.api.chat_service.SendMessageRequest
	(*CreateResponse)(nil),         // 3: chat.protobuf.api.chat_service.CreateResponse
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
}
var file_api_chat_service_service_chatServer_proto_depIdxs = []int32{
	0, // 0: chat.protobuf.api.chat_service.ChatApi.Create:input_type -> chat.protobuf.api.chat_service.CreateRequest
	1, // 1: chat.protobuf.api.chat_service.ChatApi.Delete:input_type -> chat.protobuf.api.chat_service.DeleteRequest
	2, // 2: chat.protobuf.api.chat_service.ChatApi.SendMessage:input_type -> chat.protobuf.api.chat_service.SendMessageRequest
	3, // 3: chat.protobuf.api.chat_service.ChatApi.Create:output_type -> chat.protobuf.api.chat_service.CreateResponse
	4, // 4: chat.protobuf.api.chat_service.ChatApi.Delete:output_type -> google.protobuf.Empty
	5, // 5: chat.protobuf.api.chat_service.ChatApi.SendMessage:output_type -> google.protobuf.StringValue
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_service_service_chatServer_proto_init() }
func file_api_chat_service_service_chatServer_proto_init() {
	if File_api_chat_service_service_chatServer_proto != nil {
		return
	}
	file_api_chat_service_messages_chatServer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_service_service_chatServer_proto_rawDesc), len(file_api_chat_service_service_chatServer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_service_service_chatServer_proto_goTypes,
		DependencyIndexes: file_api_chat_service_service_chatServer_proto_depIdxs,
	}.Build()
	File_api_chat_service_service_chatServer_proto = out.File
	file_api_chat_service_service_chatServer_proto_goTypes = nil
	file_api_chat_service_service_chatServer_proto_depIdxs = nil
}
