version: "3.9"
services:
  postgres:
    image: postgres 
    container_name: postgres_db
    env_file:
      - .env 
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE_NAME}

volumes:
  pgdata:
    driver: local