name: CI 

on: workflow_dispatch

run-name: CI 



jobs:
    image-build-and-push: 
        runs-on: ubuntu-latest 
        steps:
          - name: Checkout master 
            uses: actions/checkout@v4 

          - name: Login in DockerHub
            uses: docker/login-action@v3 
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build Docker image auth service
            run: docker build ./auth -t ${{ vars.DOCKERHUB_USERNAME }}/auth_service:latest
        
          - name: Send to repository auth_service
            run: docker push ${{ vars.DOCKERHUB_USERNAME }}/auth_service:latest

          - name: Build Docker image chat service 
            run: docker build ./chat -t ${{vars.DOCKERHUB_USERNAME }}/chat_service:latest

          - name: Send to repository chat_service 
            run: docker push ${{vars.DOCKERHUB_USERNAME }}/chat_service:latest

    enter-vps-and-download-images:
        needs: image-build-and-push
        runs-on: ubuntu-latest
        steps:
            - name: Enter VPS 
              uses: appleboy/ssh-action@v1.2.0
              with: 
                host: ${{secrets.HOST}}
                port: 22 
                username: ${{secrets.VPS_USERNAME}}
                password: ${{secrets.VPS_PASSWORD}}
                script: |
                    mkdir messenger2 
                    cd messenger2
                    docker pull ${{vars.DOCKERHUB_USERNAME}}/auth_service:latest 
                    docker pull ${{vars.DOCKERHUB_USERNAME}}/chat_service:latest 
                    docker run -d -p 8105:8083 --name=auth ${{vars.DOCKERHUB_USERNAME}}/auth_service:latest 
                    docker run -d -p 8106:8085 --name=chat ${{vars.DOCKERHUB_USERNAME}}/chat_service:latest
              
 
